baseurl: /flexible-jekyll
title: Hello, world! I'm myz
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 毛拥政 # add your name
author-img: david-freeman.jpg # add your photo
about-author: GitHub、jekyll真不错，使非专业的我，也可以自己编博客分享一些心得。 # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: sanfutou # add your Github handle
linkedin: # add your Linkedin handle
email: 723478279@qq.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
